# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Thomas Olsen Data Science 
email: t.olsen18@outlook.com 
description: "Thomas Olsen's student blog" 
baseurl: "" # the name of the repository 
url: "/tolsen25.github.io" #  change this to "https://<your-github-username>.github.io"
author: Thomas Olsen
copyright: TO # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description: 'The default image for the site header is a random image from 
        <a href="https://cdn.pixabay.com/photo/2016/09/05/10/02/baseball-1646091_1280.jpg" target="_blank"> baseball_bat</a>. 
        The default image for the blog post is from
        <a href="https://cdn.pixabay.com/photo/2018/10/20/14/57/ball-3760961_1280.jpg" target="_blank"
        >staidu pic from pixabay</a>.'


# Social media users names.  Leave fields blank that you don't want displayed
twitter_username: 
github_username:  tolsen25
linkedin_username: https://www.linkedin.com/in/thomas-olsen-1a0299254/
youtube_username: 
googleplus_username: 

plugins:
  - jekyll-feed

