# Set theme
remote_theme: tolsen25/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://tolsen25.github.io/'
baseurl: ''
title: 'Thomas Olsen's Portfolio'
description: 'This is my new website'
permalink: pretty
logo: "/assets/images/profileSquare.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: false
    description: "My Work"
    feature_text: |
      Blog
    feature_image: "/assets/images/fieldOpaque.png"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
      show_excerpts: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
